### ISSUE TITLE
使用 libqjs_compile.bat编译时出现了问题

### ISSUE THREAD

**Issue by aundis** [lcexc/py-quickjs#1]
PS C:\Users\85124\Downloads\py-quickjs-master> .\libqjs_compile.bat

C:\Users\85124\Downloads\py-quickjs-master>mkdir lib obj 
子目录或文件 lib 已经存在。
处理: lib 时出错。
子目录或文件 obj 已经存在。
处理: obj 时出错。

C:\Users\85124\Downloads\py-quickjs-master>gcc -Wall -Wno-array-bounds -D_GNU_SOURCE -DCONFIG_VERSION=\"2020-01-19\" -O2 -flto -c -I 
include -o obj/quickjs.o src/quickjs.c

C:\Users\85124\Downloads\py-quickjs-master>gcc -Wall -Wno-array-bounds -D_GNU_SOURCE -DCONFIG_VERSION=\"2020-01-19\" -O2 -flto -c -I 
include -o obj/libunicode.o src/libunicode.c

C:\Users\85124\Downloads\py-quickjs-master>gcc -Wall -Wno-array-bounds -D_GNU_SOURCE -DCONFIG_VERSION=\"2020-01-19\" -O2 -flto -c -I 
include -o obj/quickjs-libc.o src/quickjs-libc.c

C:\Users\85124\Downloads\py-quickjs-master>gcc -Wall -Wno-array-bounds -D_GNU_SOURCE -DCONFIG_VERSION=\"2020-01-19\" -O2 -flto -c -I 
include -o obj/libregexp.o src/libregexp.c

C:\Users\85124\Downloads\py-quickjs-master>gcc -Wall -Wno-array-bounds -D_GNU_SOURCE -DCONFIG_VERSION=\"2020-01-19\" -O2 -flto -c -I 
include -o obj/cutils.o src/cutils.c

C:\Users\85124\Downloads\py-quickjs-master>gcc -Wall -O2 -flto -c -I include -o obj/libqjs.o src/libqjs.c

C:\Users\85124\Downloads\py-quickjs-master>gcc -shared -o lib/libqjs.dll -Wl,--out-implib,lib/libqjs.lib obj/quickjs.o obj/libregexp.o obj/libunicode.o obj/cutils.o obj/quickjs-libc.o obj/libqjs.o -lm
C:\Users\85124\AppData\Local\Temp\ccKtrVjY.s: Assembler messages:
C:\Users\85124\AppData\Local\Temp\ccKtrVjY.s:12805: Error: .seh_savexmm offset is negative
C:\Users\85124\AppData\Local\Temp\ccKtrVjY.s:12806: Error: .seh_savexmm offset is negative
C:\Users\85124\AppData\Local\Temp\ccKtrVjY.s:12811: Error: .seh_savexmm offset is negative
lto-wrapper.exe: fatal error: gcc returned 1 exit status
compilation terminated.
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status

请问您是否了解这个问题呢？
或者可以留下您的QQ联系方式吗？

**Comment by lcexc** [comment]
我没有遇到这个问题,从报错信息看,可能是gcc版本过高, 我使用的是5.1

```
E:\TDM-GCC-64>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=E:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)
```

5.1.0 下载地址:  https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/
